PIAWARE_SERVER = 'localhost'
PIAWARE_PORT = 30003

TWILIO_ACCOUNT_SID = 'YOUR_TWILIO_ACCOUNT_SID'
TWILIO_AUTH_TOKEN = 'YOUR_TWILIO_AUTH_TOKEN'
TWILIO_PHONE_NUMBER = 'YOUR_TWILIO_PHONE_NUMBER'
TO_PHONE_NUMBER = 'YOUR_PHONE_NUMBER'

TARGET_HEX_MODE_S_CODES = set(['A00002'])

